name: Tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.rst'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.rst'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.12', os: ubuntu-latest, tox: py312}
          - {name: Windows, python: '3.12', os: windows-latest, tox: py312}
          - {name: Mac, python: '3.12', os: macos-latest, tox: py312}
          - {name: '3.11', python: '3.11', os: ubuntu-latest, tox: py311}
          - {name: '3.10', python: '3.10', os: ubuntu-latest, tox: py310}
          - {name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39}
          - {name: '3.8', python: '3.8', os: ubuntu-latest, tox: py38}
          - {name: '3.7', python: '3.7', os: ubuntu-latest, tox: py37}
          - {name: '3.6', python: '3.6', os: ubuntu-20.04, tox: py36}
          - {name: Style, python: '3.10', os: ubuntu-latest, tox: stylecheck}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: update pip
        run: |
          pip install -U setuptools wheel
          python -m pip install -U pip
      - run: pip install tox
      - run: tox -e ${{ matrix.tox }}
